@echo Compile gfosub.f...
@rem ifort /c /automatic /architecture:pn4 /Ob2 /MD /Gm gfosub.f
ifort /c /automatic /Ob2 /MD /Gm gfosub.f
@echo Link files...
adams07r1 cr-u n gfosub.obj -n gfosub_hmf.dll